server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: maestro-service
          uri: lb://maestro-service
          predicates:
            - Path=/maestro/**
          filters:
            - JwtAuthenticationFilter
        - id: materia-service
          uri: lb://materia-service
          predicates:
            - Path=/materia/**
          filters:
            - JwtAuthenticationFilter
        - id: alumno-service
          uri: lb://alumno-service
          predicates:
            - Path=/alumno/**
          filters:
            - JwtAuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**